const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');const nodes=new Map();function node(k){if(!nodes.has(k))nodes.set(k,{innerHTML:'',textContent:'',value:'',style:{},dataset:{},hidden:false,open:false,classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelector(){return node('nested')},append(){},showModal(){this.open=true},close(){this.open=false},remove(){},click(){},focus(){}});return nodes.get(k)}
const storage=new Map();const sandbox={console,Intl,Date,URL,AbortSignal,structuredClone,Blob,document:{querySelector:node,getElementById:id=>node('#'+id),addEventListener(){},hidden:false,body:{append(){},innerHTML:''},createElement:()=>node('created')},window:{__ARCANJU_TOKEN:'test-token',addEventListener(){}},location:{replace(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,fetch:async()=>({ok:false,status:503,json:async()=>({error:'not configured'})}),confirm:()=>true};vm.createContext(sandbox);
const script=fs.readFileSync(require('path').join(__dirname,'../private/app.html'),'utf8').match(/<script>([\s\S]*)<\/script>/)[1];vm.runInContext(script,sandbox);
const run=s=>vm.runInContext(s,sandbox);assert.ok(Math.abs(run('simulation(state).profit')-17826.26864)<0.001);
run(`applySnapshot({version:2,live:true,origin:'bridge',orders:[{id:'100',date:today(),quantity:2,revenue:249.9,shipIn:0,status:'paid',rawStatus:'open/paid',uf:'MG',city:''}],ads:[],shipping:[]})`);
assert.equal(run('state.imports.orders.length'),1);assert.equal(run('state.sales[0].ads'),249.9*.29);assert.equal(run('!!state.months[today().slice(0,7)].historyPending'),false);assert.ok(run('liveSummary().includes("249,90")'));
run(`applySnapshot({version:2,live:true,orders:[{id:'100',date:today(),quantity:2,revenue:249.9,shipIn:0,status:'excluded',rawStatus:'cancelled/paid',uf:'MG',city:''}],ads:[],shipping:[]})`);assert.equal(run('state.sales.reduce((t,r)=>t+r.revenue,0)'),0);
for(const [v] of run('navs')){sandbox.nav=v;run('view=nav;render()')}
console.log('PASS finance VM: offer baseline, new paid order, estimated ads, cancellation, 14 views render (not visual browser test)');

(async()=>{await new Promise(r=>setImmediate(r));sandbox.fetch=async()=>({ok:true,status:200,json:async()=>({version:2,live:true,origin:'bridge',orders:[{id:'101',date:run('today()'),quantity:2,revenue:249.9,shipIn:0,status:'paid',rawStatus:'open/paid',uf:'MG',city:''}],ads:[],shipping:[],queue:{last_event:new Date().toISOString(),pending:0,failed:0}})});await sandbox.pullLive();assert.equal(run("state.imports.orders.find(o=>o.id==='101').status"),'paid');await sandbox.pullLive();assert.equal(run("state.imports.orders.filter(o=>o.id==='101').length"),1);console.log('PASS automatic pull: fetch-to-import without click and no duplicate on next poll');})().catch(e=>{console.error(e);process.exitCode=1});
