import {readFile} from 'node:fs/promises';import {join} from 'node:path';import {secure} from '../lib/auth.js';import {query} from '../lib/db.js';import {EVENTS,shopRequest} from '../lib/nuvemshop.js';
export default async function handler(req,res){if(!secure(req,res))return;res.setHeader('Content-Type','application/json');if(req.method!=='POST'){res.statusCode=405;return res.end('{}')}
 try{let body=typeof req.body==='string'?JSON.parse(req.body):req.body;
 if(body?.action==='database'){const sql=await readFile(join(process.cwd(),'db/schema.sql'),'utf8');for(const s of sql.split(';').map(x=>x.trim()).filter(Boolean))await query(s);return res.end(JSON.stringify({message:'Banco preparado. Dados existentes preservados.'}))}
 if(body?.action==='register'){
 const base=process.env.APP_URL;if(!base||new URL(base).protocol!=='https:'||!process.env.NUVEMSHOP_APP_SECRET)throw Error('Configure APP_URL HTTPS e NUVEMSHOP_APP_SECRET.');await query('SELECT 1 FROM arcanju_jobs LIMIT 1');const url=new URL('/api/nuvemshop-webhook',base).href;let all=[];for(let page=1;page<=20;page++){let batch=await shopRequest('webhooks?per_page=100&page='+page);if(!Array.isArray(batch))throw Error('Resposta inválida');all.push(...batch);if(batch.length<100)break;if(page===20)throw Error('Paginação excedida')}
 let created=0;for(const event of EVENTS){if(all.some(w=>w.event===event&&w.url===url))continue;await shopRequest('webhooks',{method:'POST',body:{event,url}});created++}return res.end(JSON.stringify({message:'Avisos da Nuvemshop cadastrados: '+created+' novos. Aguardando pagamento real.',url}))}
 res.statusCode=400;res.end(JSON.stringify({error:'Ação inválida'}));
 }catch(e){res.statusCode=503;res.end(JSON.stringify({error:['Configure APP_URL HTTPS e NUVEMSHOP_APP_SECRET.','Configuração Nuvemshop pendente','Banco pendente: configure DATABASE_URL do Neon.'].includes(e.message)?e.message:'Não foi possível concluir. Confira banco, credenciais e permissões da Nuvemshop.'}))}}
